chore(rebranding): RRPproxy to CentralNic Reseller
centralnic-reseller/whmcs-ssl pull request #107
Opened 2022-08-02 09:23 UTC by AsifNawaz-cnic

2022-08-04 10:55 UTC, KaiSchwarz-cnic requested changes

2022-08-04 10:55 UTC, KaiSchwarz-cnic commented on modules/addons/cnicssl_addon/cnicssl_addon.php
> +        if (!class_exists('\WHMCS\Module\Registrar\keysystems\APIClient')) {
Wouldn't it be `\WHMCS\Module\Registrar\Keysystems\APIClient`?

2022-08-04 11:31 UTC, AsifNawaz-cnic commented on modules/addons/cnicssl_addon/cnicssl_addon.php
> +        if (!class_exists('\WHMCS\Module\Registrar\keysystems\APIClient')) {
I have fixed the requested changes, thanks for notifying

2022-08-04 17:01 UTC, KaiSchwarz-cnic commented
@AsifNawaz-cnic we need the workflow changes in place without the rebranding. Otherwise we cannot merge the workflow changes before august 31st.

2022-08-04 19:12 UTC, KaiSchwarz-cnic requested changes
See my last comment 🙋

2022-08-05 08:26 UTC, AsifNawaz-cnic commented
> @AsifNawaz-cnic we need the workflow changes in place without the rebranding. Otherwise we cannot merge the workflow changes before august 31st.

I will create a separate pull request for workflow, thanks for reminder.

2022-11-15 14:24 UTC, closed without merging